src/objects/ChannelProgramMember.object
<CustomObject>
    <fields>
        <fullName>Total_Partner_Points__c</fullName>
        <inlineHelpText>Leave this empty when changing levels and it will automatically assign the minimum points requirement of that level</inlineHelpText>
        <label>Total Partner Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Partner_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel Program</label>
        <referenceTo>ChannelProgram</referenceTo>
        <relationshipLabel>Partner Activities</relationshipLabel>
        <relationshipName>Partner_Activities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Activity__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Boolean used in Process and Triggers to check if an activity was just created or already existing</description>
        <label>New Activity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <label>Partner Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Partner Activities</relationshipLabel>
        <relationshipName>Partner_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Activity_Type__c</fullName>
        <label>Partner Activity Type</label>
        <referenceTo>Partner_Activity_Type__c</referenceTo>
        <relationshipLabel>Partner Activities</relationshipLabel>
        <relationshipName>Partner_Activities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points_Awarded__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>If left empty or untouched, it will read from the default activity type&apos;s point value</inlineHelpText>
        <label>Points Awarded</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Activity</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Partner Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Activity_Type__c.object
<CustomObject>
    <fields>
        <fullName>Points__c</fullName>
        <inlineHelpText>This is the default amount gained from an Activity. Different point values can be assigned to specific programs and levels through the Program Level Activity Point Association related list</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Activity Type</label>
    <nameField>
        <label>Partner Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Program_Level_Activity_Point_Association__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Program_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Program Level</label>
        <referenceTo>ChannelProgramLevel</referenceTo>
        <relationshipLabel>Program Level Activity Point Association</relationshipLabel>
        <relationshipName>Program_Level_Activity_Point_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Activity_Type__c</fullName>
        <label>Partner Activity Type</label>
        <referenceTo>Partner_Activity_Type__c</referenceTo>
        <relationshipLabel>Program Level Activity Point Association</relationshipLabel>
        <relationshipName>Program_Level_Activity_Point_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program Level Activity Point Association</label>
    <nameField>
        <displayFormat>PLAP-{000000}</displayFormat>
        <label>Program Level Activity Point Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Level Activity Point Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PartnerActivityPointCalculation.cls
public without sharing class PartnerActivityPointCalculation {
    @InvocableMethod(label='Assign Partner Activity Points' description='Evaluate the member and level then update their points accordingly')
    public static void AssignPartnerActivityPoints(List<Id> ActivityId) {
        List<Partner_Activity__c> activities = getActivity(ActivityId);
        if(activities != null || activities.size() > 0) {
            for(Partner_Activity__c activity : activities) {
                ChannelProgramMember member = getMember(activity.Partner_Account__c, activity.Channel_Program__c);
                
                if (member != null &&
                    Schema.sObjectType.Partner_Activity__c.fields.New_Activity__c.isUpdateable() &&
                    Schema.sObjectType.Partner_Activity__c.fields.Points_Awarded__c.isUpdateable()) {
                        // If the points awarded in an activity is not specified, search for another available point value
                        if (activity.Points_Awarded__c == null || activity.Points_Awarded__c == 0) {
                            
                            List<Program_Level_Activity_Point_Association__c> programPointAssociation = getAllProgramPointAssociations(activity.Partner_Activity_Type__c, member.LevelId); 
                            
                            // Determine whether there's a point association between the activity type and the member channel program level
                            if (programPointAssociation.size() > 0) { // If there's an association specified, use that point value
                                for(Program_Level_Activity_Point_Association__c ppa : programPointAssociation) {
                                    activity.Points_Awarded__c = ppa.Points__c;
                                }
                            }
                            else { // If there's no association specified, use the generic activity type point value
                                activity.Points_Awarded__c = activity.Partner_Activity_Type__r.Points__c;
                            }
                        }
                        // If there's a point value specified in the activity directly, use that
                        member.Total_Partner_Points__c += activity.Points_Awarded__c;
                        activity.New_Activity__c = false;
                        
                        update member;
                        update activity;
                    }
                else {
                    system.debug('User doesn\'t have access to update fields or doesn\'t belong to a Channel Program');
                }
            }
        }
        else {
            system.debug('No activities found');
        }
    }
    
    public static List<Partner_Activity__c> getActivity(List<Id> ActivityIds) {
        List<Partner_Activity__c> results = null;
        List<string> fields = new List<string> { 
            'Id',
            'Partner_Account__c',
            'New_Activity__c',
            'Partner_Activity_Type__c',
            'Channel_Program__c', 
            'Points_Awarded__c'};
        
        boolean isAccessible = FLSCheck.checkFLS(Partner_Activity__c.sObjectType.getDescribe(), fields, 'Read');
        system.debug(isAccessible);
        if (isAccessible) {
            results = [SELECT Id,
                       Partner_Account__c,
                       New_Activity__c,
                       Partner_Activity_Type__c,
                       Partner_Activity_Type__r.Points__c,
                       Channel_Program__c,
                       Points_Awarded__c
                       FROM Partner_Activity__c
                       WHERE Id IN :ActivityIds];
        }
        return results;
    }
    
    public static ChannelProgramMember getMember(Id AccountId, Id ChannelProgramId) {
        
        List<ChannelProgramMember> results = null;
        List<string> fields = new List<string> { 
            'Id',
            'LevelId',
            'Total_Partner_Points__c'};
        
        boolean isAccessible = FLSCheck.checkFLS(ChannelProgramMember.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            results = [SELECT Id,
                       LevelId,
                       Total_Partner_Points__c
                       FROM ChannelProgramMember
                       WHERE Partner.Id = :AccountId
                       AND Program.Id = :ChannelProgramId
                       LIMIT 1];
        }
        if (results.size() > 0) {
            return results[0];
        }
        else {
            return null;
        }
    }
    
    public static List<Program_Level_Activity_Point_Association__c> getAllProgramPointAssociations(Id ActivityTypeId, Id ProgramLevelId) {
        List<Program_Level_Activity_Point_Association__c> results = null;
        List<string> fields = new List<string> { 
            'Id',
            'Points__c', 
            'Channel_Program_Level__c'};
        
        boolean isAccessible = FLSCheck.checkFLS(Program_Level_Activity_Point_Association__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
        results = [SELECT Id,
                Points__c,
                Channel_Program_Level__c
                FROM Program_Level_Activity_Point_Association__c
                WHERE Partner_Activity_Type__c = :ActivityTypeId
                AND Channel_Program_Level__c = :ProgramLevelId
               	LIMIT 1];
        }
        return results;
    }
}