src/objects/ChannelProgramMember.object
<CustomObject>
    <fields>
        <fullName>Points_to_Next_Level__c</fullName>
        <formula>IF (Level.Next_Level_Point_Requirement__c &lt; Total_Partner_Points__c, 0, Level.Next_Level_Point_Requirement__c - Total_Partner_Points__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Points to Next Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Partner_Points__c</fullName>
        <inlineHelpText>Leave this empty when changing levels and it will automatically assign the minimum points requirement of that level</inlineHelpText>
        <label>Total Partner Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Partner_Activity__c.object
<CustomObject>
    <fields>
        <fullName>Partner_Activity_Type__c</fullName>
        <label>Partner Activity Type</label>
        <referenceTo>Partner_Activity_Type__c</referenceTo>
        <relationshipLabel>Partner Activities</relationshipLabel>
        <relationshipName>Partner_Activities</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Activity</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Partner Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Activity_Type__c.object
<CustomObject>
    <fields>
        <fullName>Category_Icon_URL__c</fullName>
        <formula>CASE( Category__c ,&apos;Sales&apos;, &apos;/resource/ActivityCategoryIcons/sales.svg&apos;, &apos;Service&apos;, &apos;/resource/ActivityCategoryIcons/service.svg&apos;, &apos;Conference&apos;, &apos;/resource/ActivityCategoryIcons/conference.svg&apos;, &apos;Certification&apos;, &apos;/resource/ActivityCategoryIcons/certificate.svg&apos;, &apos;&apos;)</formula>
        <label>Category Icon URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Certification</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <inlineHelpText>This is the default amount gained from an Activity. Different point values can be assigned to specific programs and levels through the Program Level Activity Point Association related list</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Activity Type</label>
    <nameField>
        <label>Partner Activity Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Activity Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Level_Requirement__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Program_Level__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Channel Program Level</label>
        <referenceTo>ChannelProgramLevel</referenceTo>
        <relationshipLabel>Partner Level Requirements</relationshipLabel>
        <relationshipName>Partner_Level_Requirements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Minimum_Point_Requirement__c</fullName>
        <description>Minimum Point Requirement for this activity type</description>
        <inlineHelpText>Minimum point requirement for this activity type</inlineHelpText>
        <label>Minimum Point Requirement</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Partner_Activity_Type__c</fullName>
        <label>Partner Activity Type</label>
        <referenceTo>Partner_Activity_Type__c</referenceTo>
        <relationshipLabel>Partner Level Requirements</relationshipLabel>
        <relationshipName>Partner_Level_Requirements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Level Requirement</label>
    <nameField>
        <label>Partner Level Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Level Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Program_Level_Activity_Point_Association__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Program_Level__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Program Level</label>
        <referenceTo>ChannelProgramLevel</referenceTo>
        <relationshipLabel>Program Level Activity Point Association</relationshipLabel>
        <relationshipName>Program_Level_Activity_Point_Association</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Featured__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick to showcase this as a featured Activity for this Channel Program Level</inlineHelpText>
        <label>Featured</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Activity_Type__c</fullName>
        <label>Partner Activity Type</label>
        <referenceTo>Partner_Activity_Type__c</referenceTo>
        <relationshipLabel>Program Level Activity Point Association</relationshipLabel>
        <relationshipName>Program_Level_Activity_Point_Association</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program Level Activity Point Association</label>
    <nameField>
        <displayFormat>PLAP-{000000}</displayFormat>
        <label>Program Level Activity Point Association</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Level Activity Point Association</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PartnerTierCommunityController.cls
public with sharing class PartnerTierCommunityController {
    
    @AuraEnabled
    public static List<ChannelProgramMember> getPartnerMembers() {
        String userId = UserInfo.getUserId();
        User user = [SELECT AccountId FROM User WHERE Id =: userId];
        List<ChannelProgramMember> partnerProgramMembers = new List<ChannelProgramMember>();
        
        if (user.AccountId != null) {
            List<string> fields = new List<string> {
                'Id',
                'LevelId',
                'PartnerId',
                'ProgramId',
                'Points_To_Next_Level__c',
                'Total_Partner_Points__c'
                };
                        
            boolean isAccessible = FLSCheck.checkFLS(ChannelProgramMember.sObjectType.getDescribe(), fields, 'Read');
            if (isAccessible) {
                partnerProgramMembers = 
                    [SELECT Id,
                     LevelId,
                     PartnerId,
                     ProgramId,
                     Points_To_Next_Level__c,
                     Total_Partner_Points__c,
                     Program.Name,
                     Level.Name,
                     Level.Icon_URL__c,
                     Level.Benefits__c,
                     Level.Next_Level__r.Name,
                     Level.Next_Level__r.Benefits__c,
                     Level.Next_Level__r.Minimum_Points__c
                     FROM ChannelProgramMember
                     WHERE PartnerId =: user.AccountId
                     ORDER BY Program.Name];
            }
            return partnerProgramMembers;
        }
        else {
            return null;
        }
    }
    
    @AuraEnabled
    public static List<Partner_Level_Requirement__c> getLevelRequirements(String levelId) {
        List<Partner_Level_Requirement__c> results = new List<Partner_Level_Requirement__c>();
        
        List<string> fields = new List<string> {'Id',
                								'Name',
                                                'Partner_Activity_Type__c',
                                                'Minimum_Point_Requirement__c'};
            
        boolean isAccessible = FLSCheck.checkFLS(Partner_Level_Requirement__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
            results = [SELECT Id,
                       Name,
                       Partner_Activity_Type__c,
                       Partner_Activity_Type__r.Name,
                       Minimum_Point_Requirement__c
                       FROM Partner_Level_Requirement__c
                       WHERE Channel_Program_Level__c = :levelId
                      ];
        }
        return results;
    }
    
    @AuraEnabled
    public static Map<Id, Integer> getMemberPointsByType (String memberId) {
        List<string> fields = new List<string> {'PartnerId',
            									'ProgramId'};
                
        boolean isAccessible = FLSCheck.checkFLS(ChannelProgramMember.sObjectType.getDescribe(), fields, 'Read');
        system.debug(isAccessible);
        if (isAccessible) {
            ChannelProgramMember member = [SELECT PartnerId, ProgramId FROM ChannelProgramMember WHERE Id =: memberId];
            return PartnerProgramLevelCalculation.getPointTypeMap(member.PartnerId, member.ProgramId);
        }
        else {
            return null;
        }
    }
    
    @AuraEnabled
    public static List<Program_Level_Activity_Point_Association__c> getFeaturedActivityTypes(String levelId) {
        List<Program_Level_Activity_Point_Association__c> results = new List<Program_Level_Activity_Point_Association__c>();
        
        List<string> fields = new List<string> {'Id',
                								'Points__c',
                                                'Partner_Activity_Type__c'};
            
        boolean isAccessible = FLSCheck.checkFLS(Program_Level_Activity_Point_Association__c.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
        results = [SELECT Id,
                   Points__c,
                   Partner_Activity_Type__r.Name,
                   Partner_Activity_Type__r.Category__c,
                   Partner_Activity_Type__r.Category_Icon_URL__c
                   FROM Program_Level_Activity_Point_Association__c
                   WHERE Channel_Program_Level__c = :levelId
                   AND Featured__c = true];
        }
        return results;
    }
    
    @AuraEnabled
    public static List<Partner_Activity__c> getActivities(String memberId) {
        List<Partner_Activity__c> results = new List<Partner_Activity__c>();
        
        List<string> fields = new List<string> {'PartnerId',
            									'ProgramId'};
                
        boolean isAccessible = FLSCheck.checkFLS(ChannelProgramMember.sObjectType.getDescribe(), fields, 'Read');
        if (isAccessible) {
        ChannelProgramMember member = [SELECT PartnerId, ProgramId FROM ChannelProgramMember WHERE Id =: memberId];
        results = PartnerProgramLevelCalculation.getActivities(member.PartnerId, member.ProgramId);
        }
        return results;
    }
}